### ISSUE TITLE
Create method

### ISSUE THREAD

**Issue by SimWhite** [thavel/synolopy#6]
Hello. Could someone explain how can I use `create` method with DownloadStation?

I'm trying to use something like API describes: `api=SYNO.DownloadStation.Task&version=1&method=create&uri=ftps://192.0.0.1:21/test/test.zip` as
`nas.downloadstation.task.request('create', {'url': 'magnet:link_here'})` but I get `TypeError: request() takes exactly 2 arguments (3 given)`.

 How can I fix it?

**Comment by thavel** [comment]
Hello @SimWhite.
Optional parameters for `.request()` are passed through `**kwargs`. So, basically, you need to call your method as follows:

``` python
nas.downloadstation.task.request('create', uri='magnet:link_here')
```

Careful with your parameters though. You tried to use `url` instead of `uri` (according to the official doc.).

But the exception raised is not very clear... I should fix this!

**Comment by SimWhite** [comment]
Oops! Everything is working fine with `uri` :)
